version: '3.7'

services:
  db:
    image: postgres:14.5
    container_name: postgres-assestment-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB?Variable not set}
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      TZ: "Asia/Jakarta"
    ports:
      - ${POSTGRES_DB_EXPOSE_PORT?Variable not set}:${POSTGRES_DB_PORT?Variable not set}
    volumes:
      - postgre_data:/var/lib/postgresql/data
      - ./data/postgres:/docker-entrypoint-initdb.d

volumes:
  postgre_data: